# Generated by Django 2.0.1 on 2019-01-16 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def create_domains(apps, schema_editor):
    Domain = apps.get_model('cxdiagnosis', 'Domain')
    Domain.objects.create(name='H & PS')
    Domain.objects.create(name='Insurance')
    Domain.objects.create(name='Travel')
    Domain.objects.create(name='Banking')
    Domain.objects.create(name='Energy')
    Domain.objects.create(name='Finance')
    Domain.objects.create(name='Retail')

class Migration(migrations.Migration):

    dependencies = [
        ('cxdiagnosis', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_domains),
        migrations.CreateModel(
            name='CapabilityArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilityareas', to='cxdiagnosis.Domain')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilityareas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Question')),
                ('capabilityarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cxdiagnosis.CapabilityArea')),
            ],
        ),
        migrations.CreateModel(
            name='ResultsOfCapabilityArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('capabilityarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_of_capability_areas', to='cxdiagnosis.CapabilityArea')),
            ],
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='domains',
            field=models.ManyToManyField(related_name='clientuser_domains', to='cxdiagnosis.Domain'),
        ),
        migrations.AddField(
            model_name='resultsofcapabilityarea',
            name='clientuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_of_capability_areas', to='cxdiagnosis.ClientUser'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='capabilityareas',
            field=models.ManyToManyField(through='cxdiagnosis.ResultsOfCapabilityArea', to='cxdiagnosis.CapabilityArea'),
        ),
    ]
